In [ ]:
# Number five

In [25]:
import numpy as np

In [20]:
MatrixA=np.array([[1, 0.2, 0.5,], [0.2, 1, 0.8,], [0.5, 0.8, 1]])
print (MatrixA)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
# (i)

In [5]:
# Transpose

In [7]:
MatrixA=np.array([[1, 0.2, 0.5,], [0.2, 1, 0.8,], [0.5, 0.8, 1]])
MatrixA.T

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [ ]:
# Determinant

In [8]:
MatrixA=np.array([[1, 0.2, 0.5,], [0.2, 1, 0.8,], [0.5, 0.8, 1]])
determinant=np.linalg.det(MatrixA)
print (determinant)

0.2299999999999999


In [ ]:
# Decomposing

In [70]:
MatrixA=np.array([[1, 0.2, 0.5,], [0.2, 1, 0.8,], [0.5, 0.8, 1]])
decomposing=np.linalg.eig(MatrixA)
print (MatrixA)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [ ]:
#Question six

In [26]:
import seaborn as sns

In [27]:
import matplotlib.pyplot as plt

In [29]:
import numpy as np

In [34]:
from numpy import random

In [ ]:
# (i)

In [37]:
PD=np.random.poisson (size=(1000))  
print (PD)       
            

[0 0 1 2 0 1 1 2 0 0 1 3 0 0 2 0 1 2 1 1 3 1 0 2 1 0 0 0 0 1 0 0 0 1 0 2 1
 0 1 0 2 1 3 0 0 1 2 2 1 0 2 2 1 1 2 0 0 1 2 1 1 0 2 0 1 4 0 3 1 1 1 0 1 2
 3 2 0 2 1 3 1 0 0 2 1 0 1 0 1 0 0 1 1 1 2 0 0 0 3 1 2 1 0 1 1 0 1 1 0 1 1
 1 1 1 0 4 0 2 1 1 2 0 1 5 2 1 0 0 1 0 3 0 0 0 1 1 1 1 2 3 0 0 1 0 0 1 1 0
 0 2 1 3 0 2 3 0 3 2 1 2 2 3 0 2 0 1 1 1 0 1 0 1 0 0 4 0 1 1 2 3 0 2 0 2 1
 2 0 0 0 0 2 1 1 0 0 0 0 0 1 0 0 0 1 2 1 3 1 0 0 5 0 3 0 0 0 2 0 2 2 1 0 1
 1 1 1 2 0 1 0 1 0 0 1 4 0 2 0 0 0 1 3 0 0 0 1 2 1 2 2 2 1 1 3 2 1 0 0 2 0
 1 0 0 1 3 0 0 2 0 0 0 1 3 0 0 1 2 1 3 0 0 0 2 0 0 0 1 0 3 0 1 3 2 1 0 2 0
 3 2 5 1 2 1 2 2 2 0 0 0 0 1 1 3 1 1 3 1 1 1 1 1 1 0 2 1 2 0 0 0 1 0 1 0 4
 0 0 2 1 2 1 1 3 0 0 1 1 0 2 0 0 0 0 0 0 1 0 1 2 0 1 0 0 1 2 1 0 1 2 3 1 0
 0 0 0 2 1 0 1 0 2 2 2 1 2 1 1 1 0 1 2 0 1 3 0 0 0 0 0 0 2 1 2 1 1 0 0 0 0
 1 1 2 2 1 0 0 2 0 1 0 1 1 0 2 0 0 0 1 0 0 0 1 1 1 2 0 3 1 4 2 1 0 0 0 0 1
 0 0 2 0 3 0 0 0 1 3 1 3 0 0 0 0 3 0 4 0 2 3 1 1 2 0 0 1 0 2 2 1 3 0 1 0 2
 3 2 3 0 2 2 2 2 0 0 0 2 

In [ ]:
# (ii)

In [73]:
PD=np.random.poisson (size=(1000)) 
mean=np.mean
print (PD)

[0 0 0 0 1 0 2 1 2 1 1 0 3 1 1 1 0 0 1 0 1 0 0 1 2 0 0 1 0 0 1 1 1 1 0 0 2
 1 0 3 1 0 1 4 1 3 3 1 1 2 2 1 0 2 1 0 1 3 0 0 0 1 3 2 2 0 1 2 3 1 2 2 3 0
 0 1 1 1 0 1 0 0 2 0 1 1 0 3 0 0 1 1 0 2 1 2 2 1 2 2 2 0 0 2 1 2 1 1 2 2 1
 2 1 1 1 0 0 2 1 1 2 2 1 0 1 1 0 0 3 1 2 1 0 0 0 1 0 1 0 2 1 1 2 0 0 0 1 3
 0 1 0 0 0 3 2 0 1 2 0 0 0 3 1 2 1 1 0 2 0 0 1 0 2 0 0 0 2 1 3 0 1 0 0 1 0
 1 0 0 0 0 2 2 1 3 2 0 0 0 1 0 1 2 2 0 1 2 1 1 0 0 2 0 1 5 1 1 1 2 1 1 0 0
 0 0 2 1 1 0 0 0 1 1 0 2 3 2 0 0 1 4 2 1 1 0 1 1 1 0 1 2 0 2 1 0 0 0 0 0 3
 1 0 3 0 1 2 3 1 4 1 1 1 1 0 1 0 2 2 0 3 0 4 2 2 0 1 0 0 1 2 1 2 2 1 1 2 1
 0 0 2 0 2 0 3 1 1 2 1 2 1 1 1 2 0 0 0 2 1 1 1 1 0 0 1 0 2 2 0 0 3 0 2 3 2
 0 0 1 2 2 2 0 2 0 1 0 1 1 1 1 1 1 1 2 0 0 3 0 2 0 2 1 0 0 0 0 0 3 1 1 0 0
 0 4 1 1 2 0 1 0 1 3 1 3 3 1 2 1 0 1 1 2 0 2 0 2 1 1 1 1 1 0 2 1 1 1 1 1 0
 1 2 1 3 1 2 1 1 0 0 2 1 0 1 1 0 0 1 1 1 0 1 0 1 0 2 1 1 3 1 0 2 1 1 1 3 0
 1 2 0 1 1 0 1 2 1 2 4 4 0 0 0 1 0 1 0 1 4 1 0 1 1 0 2 0 0 1 1 1 0 1 1 2 2
 1 0 1 3 3 1 0 1 0 2 1 1 

In [ ]:
# variance

In [74]:
PD=np.random.poisson (size=(1000))
variance= np.var
print (PD)

[1 0 2 1 0 0 1 0 1 0 3 2 1 1 1 0 2 0 0 1 0 0 0 4 0 1 0 4 1 1 2 2 1 1 1 1 1
 0 0 1 0 3 2 1 1 0 0 1 0 1 0 2 2 0 2 2 0 1 1 1 3 2 1 0 1 2 3 1 0 1 2 2 0 1
 0 2 1 0 2 0 1 0 1 0 1 1 1 0 3 3 1 1 0 1 0 0 0 1 1 2 1 0 0 0 0 0 0 2 0 0 0
 2 1 1 0 3 0 3 3 2 1 0 0 3 1 0 1 3 1 0 0 1 0 1 1 1 1 3 2 0 0 0 0 1 1 0 0 0
 0 2 0 1 1 1 0 0 0 3 1 0 0 0 1 2 2 2 1 0 1 1 0 3 1 0 1 2 3 0 4 2 1 0 2 1 2
 0 2 1 0 1 0 0 0 1 2 0 2 3 1 0 0 0 0 0 0 2 2 0 1 0 0 2 1 2 1 1 0 0 0 4 2 1
 2 0 1 2 0 0 0 2 1 0 0 0 0 2 0 1 2 2 1 2 0 2 0 0 1 0 3 1 4 1 1 1 0 0 2 1 3
 1 1 2 0 1 0 0 1 2 1 1 2 0 1 1 0 1 1 1 0 1 4 1 0 4 1 4 1 2 1 3 0 0 1 1 1 0
 4 1 1 0 0 2 1 2 2 1 3 2 1 2 0 1 0 2 1 0 0 4 1 1 0 2 1 1 1 0 0 2 1 1 1 0 0
 2 2 2 0 0 0 0 0 1 0 0 1 1 3 0 2 0 0 2 2 2 2 0 0 2 2 3 0 2 0 0 2 5 1 2 1 0
 2 2 1 1 1 2 3 0 1 0 0 1 3 0 1 2 2 1 0 0 3 0 0 1 1 2 0 0 0 1 0 2 1 0 1 1 3
 1 1 3 0 1 0 0 0 1 1 4 1 0 0 2 0 1 1 1 2 1 1 1 1 1 1 0 0 1 2 0 0 0 3 1 0 1
 1 0 1 1 2 0 1 0 3 0 0 2 2 0 1 0 2 1 1 2 2 1 0 1 2 0 0 2 1 2 0 1 1 1 0 2 2
 3 0 2 0 2 2 0 1 0 1 0 3 

In [75]:

plt.show

<function matplotlib.pyplot.show(*args, **kwargs) -> 'None'>